service: externals
frameworkVersion: '3'
bref:
    team: bref

provider:
    name: aws
    region: eu-west-1
    stage: prod
    runtime: provided.al2
    layers:
        - ${bref:layer.php-81}
    timeout: 10
    environment:
        APP_ENV: prod
        EXTERNALS_APP_VERSION: ${env:GITHUB_RUN_ID}
        DATABASE_NAME: 'externals-prod'
        DATABASE_HOST: ${ssm:/externals/db/host}
        DATABASE_PORT: 3306
        DATABASE_USER: ${ssm:/externals/db/user}
        DATABASE_PASSWORD: ${ssm:/externals/db/password}
        ALGOLIA_APP_ID: KSTITII7EC
        ALGOLIA_API_KEY: ${ssm:/externals/algolia_api_key}
        ALGOLIA_INDEX_PREFIX: ${param:algoliaIndexPrefix}
        GITHUB_OAUTH_CLIENT_ID: ${param:githubOAuthClientId}
        GITHUB_OAUTH_CLIENT_SECRET: ${ssm:/externals/github_oauth_client_secret}
        GITHUB_OAUTH_REDIRECT_URL: 'https://externals.io/login'
        SENTRY_URL: ${ssm:/externals/sentry_url}
        SESSION_SECRET_KEY: ${ssm:/externals/session_secret_key}
        # See https://bref.sh/docs/environment/performances.html#bref-for-event-driven-functions
        BREF_LOOP_MAX: '100'

params:
    prod:
        isProd: true
        algoliaIndexPrefix: v2_
        githubOAuthClientId: b75b3226c86d801a95cd
    default:
        isProd: false
        algoliaIndexPrefix: dev_
        githubOAuthClientId: 422ae3a54f6ebd43895b

package:
    exclude:
        - '.github/**'
        - 'assets/**'
        - 'backups/**'
        - 'node_modules/**'
        - 'tests/**'
        - 'var/log/**'
        - 'web/**'

functions:
    home:
        handler: Externals\Application\Controller\HomeController
        events:
            - httpApi: 'GET /'
    thread:
        handler: Externals\Application\Controller\ThreadController
        events:
            - httpApi: 'GET /message/{number}'
    top:
        handler: Externals\Application\Controller\TopController
        events:
            - httpApi: 'GET /top'
    news:
        handler: Externals\Application\Controller\NewsController
        events:
            - httpApi: 'GET /news'
    login:
        handler: Externals\Application\Controller\LoginController
        events:
            - httpApi: 'GET /login'
    logout:
        handler: Externals\Application\Controller\LogoutController
        events:
            - httpApi: 'GET /logout'
    email-source:
        handler: Externals\Application\Controller\EmailSourceController
        events:
            - httpApi: 'GET /email/{number}/source'
    stats:
        handler: Externals\Application\Controller\StatsController
        events:
            - httpApi: 'GET /stats'
    vote:
        handler: Externals\Application\Controller\VoteController
        events:
            - httpApi: 'POST /votes/{number}'
    rss:
        handler: Externals\Application\Controller\RssController
        events:
            - httpApi: 'GET /rss'
    rss-rfc:
        handler: Externals\Application\Controller\RssRfcController
        events:
            - httpApi: 'GET /rss-rfc'
    # Keep backward compatibility with old URLs (old threads)
    legacy-thread-redirect:
        handler: Externals\Application\Controller\LegacyThreadRedirectController
        events:
            - httpApi: 'GET /thread/{id}'
    # Catch-all to render a "Not found" page
    not-found:
        handler: Bref\Micro\Http\ThrowNotFound
        events:
            - httpApi: '*'

    # This script fetches emails from the mailing list and updates our database
    updater:
        handler: Externals\Application\Handler\SynchronizeHandler
        description: 'externals.io updater'
        timeout: 900
        environment:
            BREF_LOOP_MAX: '1'
        events:
            -   schedule:
                    rate: rate(15 minutes)
                    # Only enabled in production
                    enabled: ${param:isProd}

    console:
        handler: console
        timeout: 900
        layers:
            - ${bref:layer.php-81}
            - ${bref:layer.console}

plugins:
    - ./vendor/bref/bref
    - serverless-lift

constructs:
    website:
        type: server-side-website
        assets:
            '/assets/*': web/assets
        domain: externals.io
        certificate: arn:aws:acm:us-east-1:416566615250:certificate/0f28e63d-d3a9-4578-9f8b-14347bfe8326
