name: build

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'

            -   name: Git checkout
                uses: actions/checkout@v2

            -   name: Install Composer dependencies
                run: composer install --no-interaction --no-progress --no-suggest --ignore-platform-reqs

            -   name: Run PHPUnit
                run: vendor/bin/phpunit --colors=always
