name: Deploy

on:
    push:
        branches: ['master']

jobs:

    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:

            -   uses: actions/checkout@v4

            -   uses: actions/setup-node@v4
                with:
                    node-version: '18'

            -   name: Cache npm dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.npm # npm cache files are stored in `~/.npm`
                    key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.OS }}-node-

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.0'
                    tools: bref/cli:dev-main

            -   uses: ramsey/composer-install@v3
                with:
                    composer-options: '--optimize-autoloader --no-dev --ignore-platform-reqs'

            -   run: npm ci

            -   run: make assets-prod

            -   run: bref deploy --env=prod
                env:
                    BREF_TOKEN: ${{ secrets.BREF_TOKEN }}
